#include "fc_magic_visual.h"
#include <stddef.h>

/* Spell profiles from RuneC's reviewed B237 combat_visuals snapshot. */
static const struct {
    int spell, weapon;
    FcPlayerVisualProfile profile;
} PROFILES[] = {
    {30, 0, {.attack_anim=1162,
     .projectile_launch_spot=90, .projectile_travel_spot=91, .projectile_impact_spot=92,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {14, 0, {.attack_anim=1163,
     .projectile_launch_spot=102, .projectile_travel_spot=103, .projectile_impact_spot=104,
     .projectile_start_height=144, .projectile_end_height=124, .projectile_launch_delay_client_ticks=61,
     .projectile_angle=16, .projectile_length_adjustment=-15, .projectile_progress=64, .projectile_step_multiplier=10}},
    {37, 0, {.attack_anim=1162,
     .projectile_launch_spot=93, .projectile_travel_spot=94, .projectile_impact_spot=95,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {20, 0, {.attack_anim=1162,
     .projectile_launch_spot=96, .projectile_travel_spot=97, .projectile_impact_spot=98,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {60, 0, {.attack_anim=1164,
     .projectile_launch_spot=105, .projectile_travel_spot=106, .projectile_impact_spot=107,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {21, 0, {.attack_anim=1162,
     .projectile_launch_spot=99, .projectile_travel_spot=100, .projectile_impact_spot=101,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {36, 0, {.attack_anim=1162,
     .projectile_launch_spot=117, .projectile_travel_spot=118, .projectile_impact_spot=119,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {61, 0, {.attack_anim=1165,
     .projectile_launch_spot=108, .projectile_travel_spot=109, .projectile_impact_spot=110,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {62, 0, {.attack_anim=1161,
     .projectile_launch_spot=177, .projectile_travel_spot=178, .projectile_impact_spot=181,
     .projectile_start_height=180, .projectile_end_height=0, .projectile_launch_delay_client_ticks=75,
     .projectile_angle=16, .projectile_length_adjustment=-29, .projectile_progress=64, .projectile_step_multiplier=10}},
    {34, 0, {.attack_anim=1162,
     .projectile_launch_spot=120, .projectile_travel_spot=121, .projectile_impact_spot=122,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {19, 0, {.attack_anim=1162,
     .projectile_launch_spot=123, .projectile_travel_spot=124, .projectile_impact_spot=125,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {2, 0, {.attack_anim=1162,
     .projectile_launch_spot=126, .projectile_travel_spot=127, .projectile_impact_spot=128,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {15, 0, {.attack_anim=1166,
     .projectile_launch_spot=145, .projectile_travel_spot=146, .projectile_impact_spot=147,
     .projectile_start_height=124, .projectile_end_height=124, .projectile_launch_delay_client_ticks=46,
     .projectile_angle=16, .projectile_length_adjustment=0, .projectile_progress=64, .projectile_step_multiplier=5}},
    {43, 0, {.attack_anim=1162,
     .projectile_launch_spot=132, .projectile_travel_spot=133, .projectile_impact_spot=134,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {26, 0, {.attack_anim=1162,
     .projectile_launch_spot=135, .projectile_travel_spot=136, .projectile_impact_spot=137,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {11, 0, {.attack_anim=708,
     .projectile_launch_spot=87, .projectile_travel_spot=88, .projectile_impact_spot=89,
     .projectile_start_height=144, .projectile_end_height=124, .projectile_launch_delay_client_ticks=60,
     .projectile_angle=16, .projectile_length_adjustment=-14, .projectile_progress=64, .projectile_step_multiplier=10}},
    {46, 0, {.attack_anim=1576,
     .projectile_launch_spot=0, .projectile_travel_spot=328, .projectile_impact_spot=329,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {63, 0, {.attack_anim=1161,
     .projectile_launch_spot=177, .projectile_travel_spot=178, .projectile_impact_spot=180,
     .projectile_start_height=180, .projectile_end_height=0, .projectile_launch_delay_client_ticks=75,
     .projectile_angle=16, .projectile_length_adjustment=-29, .projectile_progress=64, .projectile_step_multiplier=10}},
    {44, 0, {.attack_anim=1162,
     .projectile_launch_spot=138, .projectile_travel_spot=139, .projectile_impact_spot=140,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {1, 0, {.attack_anim=1162,
     .projectile_launch_spot=129, .projectile_travel_spot=130, .projectile_impact_spot=131,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {16, 0, {.attack_anim=811,
     .projectile_launch_spot=0, .projectile_travel_spot=0, .projectile_impact_spot=76,
     .projectile_start_height=0, .projectile_end_height=0, .projectile_launch_delay_client_ticks=0,
     .projectile_angle=0, .projectile_length_adjustment=0, .projectile_progress=0, .projectile_step_multiplier=0}},
    {23, 0, {.attack_anim=811,
     .projectile_launch_spot=0, .projectile_travel_spot=0, .projectile_impact_spot=78,
     .projectile_start_height=0, .projectile_end_height=0, .projectile_launch_delay_client_ticks=0,
     .projectile_angle=0, .projectile_length_adjustment=0, .projectile_progress=0, .projectile_step_multiplier=0}},
    {31, 0, {.attack_anim=811,
     .projectile_launch_spot=0, .projectile_travel_spot=0, .projectile_impact_spot=1511,
     .projectile_start_height=0, .projectile_end_height=0, .projectile_launch_delay_client_ticks=0,
     .projectile_angle=0, .projectile_length_adjustment=0, .projectile_progress=0, .projectile_step_multiplier=0}},
    {45, 0, {.attack_anim=1167,
     .projectile_launch_spot=158, .projectile_travel_spot=159, .projectile_impact_spot=160,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {35, 0, {.attack_anim=1167,
     .projectile_launch_spot=161, .projectile_travel_spot=162, .projectile_impact_spot=163,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {64, 0, {.attack_anim=811,
     .projectile_launch_spot=167, .projectile_travel_spot=168, .projectile_impact_spot=169,
     .projectile_start_height=144, .projectile_end_height=124, .projectile_launch_delay_client_ticks=34,
     .projectile_angle=16, .projectile_length_adjustment=12, .projectile_progress=64, .projectile_step_multiplier=10}},
    {13, 0, {.attack_anim=1167,
     .projectile_launch_spot=164, .projectile_travel_spot=165, .projectile_impact_spot=166,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {65, 0, {.attack_anim=1168,
     .projectile_launch_spot=170, .projectile_travel_spot=171, .projectile_impact_spot=172,
     .projectile_start_height=144, .projectile_end_height=124, .projectile_launch_delay_client_ticks=48,
     .projectile_angle=16, .projectile_length_adjustment=-2, .projectile_progress=64, .projectile_step_multiplier=10}},
    {3, 0, {.attack_anim=1167,
     .projectile_launch_spot=155, .projectile_travel_spot=156, .projectile_impact_spot=157,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {66, 0, {.attack_anim=1161,
     .projectile_launch_spot=177, .projectile_travel_spot=178, .projectile_impact_spot=179,
     .projectile_start_height=180, .projectile_end_height=0, .projectile_launch_delay_client_ticks=75,
     .projectile_angle=16, .projectile_length_adjustment=-29, .projectile_progress=64, .projectile_step_multiplier=10}},
    {67, 0, {.attack_anim=1169,
     .projectile_launch_spot=173, .projectile_travel_spot=174, .projectile_impact_spot=175,
     .projectile_start_height=144, .projectile_end_height=124, .projectile_launch_delay_client_ticks=52,
     .projectile_angle=16, .projectile_length_adjustment=-6, .projectile_progress=64, .projectile_step_multiplier=10}},
    {158, 0, {.attack_anim=7855,
     .projectile_launch_spot=1455, .projectile_travel_spot=1456, .projectile_impact_spot=1457,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {159, 0, {.attack_anim=7855,
     .projectile_launch_spot=1458, .projectile_travel_spot=1459, .projectile_impact_spot=1460,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {160, 0, {.attack_anim=7855,
     .projectile_launch_spot=1461, .projectile_travel_spot=1462, .projectile_impact_spot=1463,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {161, 0, {.attack_anim=7855,
     .projectile_launch_spot=1464, .projectile_travel_spot=1465, .projectile_impact_spot=1466,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {28, 0, {.attack_anim=1978,
     .projectile_launch_spot=0, .projectile_travel_spot=384, .projectile_impact_spot=385,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {29, 0, {.attack_anim=1978,
     .projectile_launch_spot=0, .projectile_travel_spot=378, .projectile_impact_spot=379,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {88, 0, {.attack_anim=1978,
     .projectile_launch_spot=0, .projectile_travel_spot=372, .projectile_impact_spot=373,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {7, 0, {.attack_anim=1978,
     .projectile_launch_spot=0, .projectile_travel_spot=360, .projectile_impact_spot=361,
     .projectile_start_height=172, .projectile_end_height=0, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {96, 0, {.attack_anim=1979,
     .projectile_launch_spot=0, .projectile_travel_spot=388, .projectile_impact_spot=389,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {119, 0, {.attack_anim=1979,
     .projectile_launch_spot=0, .projectile_travel_spot=0, .projectile_impact_spot=382,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {85, 0, {.attack_anim=1979,
     .projectile_launch_spot=0, .projectile_travel_spot=0, .projectile_impact_spot=376,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {6, 0, {.attack_anim=1979,
     .projectile_launch_spot=0, .projectile_travel_spot=366, .projectile_impact_spot=367,
     .projectile_start_height=172, .projectile_end_height=0, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {121, 0, {.attack_anim=1978,
     .projectile_launch_spot=0, .projectile_travel_spot=386, .projectile_impact_spot=387,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {120, 0, {.attack_anim=1978,
     .projectile_launch_spot=0, .projectile_travel_spot=380, .projectile_impact_spot=381,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {118, 0, {.attack_anim=1978,
     .projectile_launch_spot=0, .projectile_travel_spot=374, .projectile_impact_spot=375,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {5, 0, {.attack_anim=1978,
     .projectile_launch_spot=0, .projectile_travel_spot=362, .projectile_impact_spot=363,
     .projectile_start_height=172, .projectile_end_height=0, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {82, 0, {.attack_anim=1979,
     .projectile_launch_spot=0, .projectile_travel_spot=390, .projectile_impact_spot=391,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {97, 0, {.attack_anim=1979,
     .projectile_launch_spot=0, .projectile_travel_spot=0, .projectile_impact_spot=383,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {58, 0, {.attack_anim=1979,
     .projectile_launch_spot=0, .projectile_travel_spot=0, .projectile_impact_spot=377,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {4, 0, {.attack_anim=1979,
     .projectile_launch_spot=0, .projectile_travel_spot=368, .projectile_impact_spot=369,
     .projectile_start_height=172, .projectile_end_height=0, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {166, 0, {.attack_anim=8972,
     .projectile_launch_spot=1856, .projectile_travel_spot=0, .projectile_impact_spot=1857,
     .projectile_start_height=0, .projectile_end_height=0, .projectile_launch_delay_client_ticks=0,
     .projectile_angle=0, .projectile_length_adjustment=0, .projectile_progress=0, .projectile_step_multiplier=0}},
    {169, 0, {.attack_anim=8977,
     .projectile_launch_spot=1865, .projectile_travel_spot=0, .projectile_impact_spot=1866,
     .projectile_start_height=0, .projectile_end_height=0, .projectile_launch_delay_client_ticks=0,
     .projectile_angle=0, .projectile_length_adjustment=0, .projectile_progress=0, .projectile_step_multiplier=0}},
    {167, 0, {.attack_anim=8972,
     .projectile_launch_spot=1859, .projectile_travel_spot=0, .projectile_impact_spot=1860,
     .projectile_start_height=0, .projectile_end_height=0, .projectile_launch_delay_client_ticks=0,
     .projectile_angle=0, .projectile_length_adjustment=0, .projectile_progress=0, .projectile_step_multiplier=0}},
    {170, 0, {.attack_anim=8977,
     .projectile_launch_spot=1867, .projectile_travel_spot=0, .projectile_impact_spot=1868,
     .projectile_start_height=0, .projectile_end_height=0, .projectile_launch_delay_client_ticks=0,
     .projectile_angle=0, .projectile_length_adjustment=0, .projectile_progress=0, .projectile_step_multiplier=0}},
    {168, 0, {.attack_anim=8972,
     .projectile_launch_spot=1862, .projectile_travel_spot=0, .projectile_impact_spot=1863,
     .projectile_start_height=0, .projectile_end_height=0, .projectile_launch_delay_client_ticks=0,
     .projectile_angle=0, .projectile_length_adjustment=0, .projectile_progress=0, .projectile_step_multiplier=0}},
    {171, 0, {.attack_anim=8977,
     .projectile_launch_spot=1869, .projectile_travel_spot=0, .projectile_impact_spot=1870,
     .projectile_start_height=0, .projectile_end_height=0, .projectile_launch_delay_client_ticks=0,
     .projectile_angle=0, .projectile_length_adjustment=0, .projectile_progress=0, .projectile_step_multiplier=0}},
    {0, 11905, {.attack_anim=1167,
     .projectile_launch_spot=1251, .projectile_travel_spot=1252, .projectile_impact_spot=1253,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {0, 11907, {.attack_anim=1167,
     .projectile_launch_spot=1251, .projectile_travel_spot=1252, .projectile_impact_spot=1253,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {0, 12899, {.attack_anim=1167,
     .projectile_launch_spot=665, .projectile_travel_spot=1040, .projectile_impact_spot=1042,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {0, 22288, {.attack_anim=1167,
     .projectile_launch_spot=1251, .projectile_travel_spot=1252, .projectile_impact_spot=1253,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {0, 22292, {.attack_anim=1167,
     .projectile_launch_spot=665, .projectile_travel_spot=1040, .projectile_impact_spot=1042,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {0, 22323, {.attack_anim=1167,
     .projectile_launch_spot=1540, .projectile_travel_spot=1539, .projectile_impact_spot=1541,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {0, 25731, {.attack_anim=1167,
     .projectile_launch_spot=1900, .projectile_travel_spot=1899, .projectile_impact_spot=1901,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {0, 27275, {.attack_anim=9493,
     .projectile_launch_spot=2125, .projectile_travel_spot=2126, .projectile_impact_spot=2127,
     .projectile_start_height=250, .projectile_end_height=124, .projectile_launch_delay_client_ticks=56,
     .projectile_angle=32, .projectile_length_adjustment=16, .projectile_progress=40, .projectile_step_multiplier=10}},
    {0, 22555, {.attack_anim=1167,
     .projectile_launch_spot=0, .projectile_travel_spot=2340, .projectile_impact_spot=0,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {0, 27665, {.attack_anim=1167,
     .projectile_launch_spot=0, .projectile_travel_spot=2337, .projectile_impact_spot=0,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {0, 28585, {.attack_anim=10501,
     .projectile_launch_spot=2567, .projectile_travel_spot=2569, .projectile_impact_spot=2568,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {0, 31113, {.attack_anim=12397,
     .projectile_launch_spot=3366, .projectile_travel_spot=3367, .projectile_impact_spot=3368,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {0, 22516, {.attack_anim=1167,
     .projectile_launch_spot=1543, .projectile_travel_spot=1544, .projectile_impact_spot=1545,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {0, 33314, {.attack_anim=1167,
     .projectile_launch_spot=3722, .projectile_travel_spot=3724, .projectile_impact_spot=3726,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {0, 33318, {.attack_anim=1167,
     .projectile_launch_spot=3722, .projectile_travel_spot=3724, .projectile_impact_spot=3726,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {0, 33322, {.attack_anim=1167,
     .projectile_launch_spot=3721, .projectile_travel_spot=3723, .projectile_impact_spot=3725,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {0, 33323, {.attack_anim=1167,
     .projectile_launch_spot=3721, .projectile_travel_spot=3723, .projectile_impact_spot=3725,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
    {0, 33326, {.attack_anim=1167,
     .projectile_launch_spot=3721, .projectile_travel_spot=3723, .projectile_impact_spot=3725,
     .projectile_start_height=172, .projectile_end_height=124, .projectile_launch_delay_client_ticks=51,
     .projectile_angle=16, .projectile_length_adjustment=-5, .projectile_progress=64, .projectile_step_multiplier=10}},
};

const FcPlayerVisualProfile *fc_magic_visual_profile(int spell, int weapon) {
    for (unsigned i=0; i<sizeof(PROFILES)/sizeof(PROFILES[0]); i++)
        if (spell ? PROFILES[i].spell == spell : !PROFILES[i].spell && PROFILES[i].weapon == weapon)
            return &PROFILES[i].profile;
    return NULL;
}

